namespace PrismLauncherWinUI3
{
    [default_interface]
    runtimeclass App : Microsoft.UI.Xaml.Application
    {
        App();
        void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args);
    }
}